spending_control/api/urls.py
from django.urls import path
from .views import SpendingControlListCreateAPIView, SpendingRetrieveAPIView, generate_liquidation_certificate

urlpatterns = [
    path('api/spendings/', SpendingControlListCreateAPIView.as_view(), name='spending-list-create'),
    path('api/spendings/<int:pk>/', SpendingRetrieveAPIView.as_view(), name='spending-retrieve'),
    path('generate-liquidation-certificate/<int:pk>/', generate_liquidation_certificate, name='generate-liquidation-certificate'),
]

spending_control/urls.py
from django.urls import path

from spending_control.api.urls import urlpatterns as api_urlpatterns

from spending_control.views import SpendingListView

app_name = 'spending_control'

urlpatterns = [
    path('spendings/', SpendingListView.as_view(), name='spending-list'),
]

urlpatterns += api_urlpatterns

test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from test_project.views import IndexView, SignInView, SignOutView

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path('', include("spending_control.urls")),
    
    path('login/', SignInView.as_view(), name="login"),
    path('logout/', SignOutView.as_view(), name="logout"),
]

spending_control/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Spending(models.Model):
    class SPENDING_TYPE(models.TextChoices):
        INVOICED = 'INVOICED', 'Facturado'
        NOT_INVOICED = 'NOT_INVOICED', 'No Facturado'

    class STATUS(models.TextChoices):
        PENDING = 'PENDING', 'Pendiente'
        FINISHED = 'FINISHED', 'Finalizado'
        DELETED = 'DELETED', 'Eliminado'

    created_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name='spendings_registered')
    created_at = models.DateTimeField(auto_now_add=True)
    liquidations = models.ManyToManyField(
        'Liquidation',
        related_name='spendings_registered')
    liquidation_sent = models.FileField(
        upload_to='liquidation_sent/',
        null=True, blank=True)
    account_status = models.FileField(
        upload_to='account_status/', null=True, blank=True)
    liquidation_certificate = models.FileField(
        upload_to='liquidation_certificate/', null=True, blank=True)
    signed_liquidation_certificate = models.FileField(
        upload_to='signed_liquidation_certificate/', null=True, blank=True)
    invoice = models.FileField(
        upload_to='invoice/', null=True, blank=True)
    type = models.CharField(
        max_length=100,
        choices=SPENDING_TYPE.choices,
        default=SPENDING_TYPE.NOT_INVOICED)
    status = models.CharField(
        max_length=100,
        choices=STATUS.choices,
        default=STATUS.PENDING)
    totals_match = models.BooleanField(default=True)
    justification = models.TextField(null=True, blank=True)

    @property
    def can_generate_liquidation_certificate(self):
        if self.type == self.SPENDING_TYPE.INVOICED:
            required_fields_present = all([
                self.liquidation_sent,
                self.account_status,
                self.invoice,
                (self.liquidation_certificate is None or self.liquidation_certificate == '')
            ])
        else:
            required_fields_present = all([
                self.liquidation_sent,
                self.account_status,
                (self.liquidation_certificate is None or self.liquidation_certificate == '')
            ])
        return required_fields_present

    def __str__(self):
        return f'Spending {self.id} - {self.description}'


class Liquidation(models.Model):
    date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f'Liquidation {self.id} - Amount: {self.amount}'

spending_control/api/views.py
import io

from django.http import HttpResponse
from django.db.models import Sum
from django.conf import settings
from django.db import transaction

from openpyxl import load_workbook
from openpyxl.styles import Protection

from decimal import Decimal

from pathlib import Path
from django.urls import path

from rest_framework.generics import ListCreateAPIView, RetrieveUpdateAPIView
from rest_framework.response import Response
from rest_framework import status

from spending_control.models import Spending
from spending_control.api.serializers import SpendingSerializer


class SpendingControlListCreateAPIView(ListCreateAPIView):
    queryset = Spending.objects.all()
    serializer_class = SpendingSerializer


class SpendingRetrieveAPIView(RetrieveUpdateAPIView):
    queryset = Spending.objects.all()
    serializer_class = SpendingSerializer

    def partial_update(self, request, *args, **kwargs):
        
        return Response({'message': 'OK'}, status=status.HTTP_206_PARTIAL_CONTENT)


def generate_liquidation_certificate(request, pk):
    instance = Spending.objects.get(pk=pk)
    liquidations = instance.liquidations.all()

    file_path = Path(settings.BASE_DIR) / 'spending_control' / 'templates' / 'spending_control' / 'liquidation_certificate.xlsx'
    file_path = Path(file_path)
    
    buffer = io.BytesIO()
    
    wb = load_workbook(file_path)
    ws = wb['CONOCIMIENTO']
    
    ws.protection.sheet = True
    ws.protection.password = 'Archivo de prueba'
    
    unlock_cells = ws['A1:S50']
    
    for item in unlock_cells:
        for cell in item:
            if cell.row != 20:
                cell.protection = Protection(locked=False)
                
                
    detail = 'A continuación se adjuntan los siguientes comprobantes:\n\n'
    
    for liquidation in liquidations:
        detail += f'{liquidation.entity} {liquidation.invoice_number} {liquidation.total_value}\n'
        
    ws['B20'] = detail
    
    wb.save(buffer)
    buffer.seek(0)
    
    instance.liquidation_certificate.save('Conocimiento_Prueba.xlsx', buffer)
    instance.save()
    
    response = HttpResponse(content_type='application/ms-excel')
    contenido = 'attachment; filename={}'.format(
        f'Conocimiento_Prueba.xlsx')
    response['Content-Disposition'] = contenido
    wb.save(response)
    
    return response

spending_control/views.py
from urllib.parse import urlparse
from django.core.paginator import Paginator
from django_filters.views import FilterView

from spending_control.models import Spending
from spending_control.filters import SpendingFilter


class SpendingListView(FilterView):
    template_name = 'spending_control/spending_list.html'
    context_object_name = 'spendings'
    queryset = Spending.objects.all().order_by('-created_at')
    filterset_class = SpendingFilter
    pag_by = 10
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        parse_url = urlparse(self.request.build_absolute_uri())
        base_url = parse_url.scheme + "://" + parse_url.netloc + parse_url.path
        base_url += '?page=1'

        
        list_filter = [
            {'label': 'Ver todos', 'url': base_url},
            {'label': 'Pendiente de estado de cuenta',
                'url': f'{base_url}&account_status=False'},
            {'label': 'Pendiente de factura', 'url': f'{base_url}&invoice=False'},
            {'label': 'Pendiente de conocimiento firmado',
                'url': f'{base_url}&liquidation_certificate=False'},
        ]
        context['filters'] = list_filter
        
        return context

spending_control/templates/spending_control/spending_list.html
{% extends "base.html" %} {% load static %} 
{% block title %} Lista de cobros {% endblock title %} 
{% block cdns %} {% endblock cdns %} {% block main %}

<div id="spending-list">
  <h2 class="text-center">Lista de cobros</h2>
  <span> </span>
  <main class="mt-3 p-3">
    <section id="button-group">
      <div class="btn-group">
        <button
          type="button"
          class="btn btn-danger dropdown-toggle btn-sm"
          data-toggle="dropdown"
          aria-expanded="false"
        >
          Ver por
        </button>

        <div class="dropdown-menu">
          {% for item in filters %}
          <a href="{{ item.url }}" class="dropdown-item"> {{ item.label }} </a>
          {% endfor %}
        </div>
      </div>
    </section>

    <section id="table-spendings">
      <div class="table-responsive mt-3">
        <table class="table table-sm table-bordered table-hover">
          <thead class="thead-dark text-center">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Tipo de cobro</th>
              <th scope="col">Liquidacion enviada</th>
              <th scope="col">Estado de cuenta</th>
              <th scope="col">Factura (Si aplica)</th>
              <th scope="col">
                Conocimiento firmado <br />
                por el cliente
              </th>
              <th scope="col">Estado</th>
              <th scope="col">Opciones</th>
            </tr>
          </thead>
          <tbody>
            {% for spending in spendings %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ spending.get_type_display }}</td>
              <td>
                <a href="{{ spending.liquidation_sent.url }}">
                  Ver documento
                </a>
              </td>

              <td>
                {% if spending.account_status != '' or spending.account != None %}
                <a href="{{ spending.account_status.url }}"> Ver documento </a>
                {% else %} Pendiente {% endif %}
              </td>

              <td v-if="'{{ spending.type }}' == 'INVOICED'">
                <a
                  href="{{ spending.invoice }}"
                  v-if="'{{ spending.invoice }}' != ''"
                >
                  Ver documento
                </a>
                <span v-else> Pendiente </span>
              </td>

              <td v-else>No aplica</td>

              <td>
                {% if spending.signed_liquidation_certificate != '' and spending.signed_liquidation_certificate %}
                <a href="{{ spending.signed_liquidation_certificate }}">
                  Ver documento
                </a>
                {% else %} Pendiente {% endif %}
              </td>

              <td>{{ spending.get_status_display }}</td>

              {% if spending.signed_liquidation_certificate != '' and spending.signed_liquidation_certificate != None %}
              <td>Proceso finalizado</td>
              {% else %}

              <td>
                {% include "spending_control/components/action_buttons.html" with data=spending %}
              </td>

              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      {% include "spending_control/components/pagination.html" %} 
      {% include "spending_control/components/modals/document_modal.html" %} 
      {% include "spending_control/components/modals/justification_modal.html" %} 
      {% include "spending_control/components/modals/show_justification_modal.html" %}
    </section>
  </main>
</div>

{% endblock main %} {% block scripts %}
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script type="module" src="{% static 'js/spendings/list.js' %}"></script>
{% endblock scripts %}