spending_control/urls.py
from django.urls import path

from spending_control.api.urls import urlpatterns as api_urlpatterns

from spending_control.views import SpendingListView

app_name = 'spending_control'

urlpatterns = [
    path('spendings/', SpendingListView.as_view(), name='spending-list'),
]

urlpatterns += api_urlpatterns

test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from test_project.views import IndexView, SignInView, SignOutView

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path('', include("spending_control.urls")),
    
    path('login/', SignInView.as_view(), name="login"),
    path('logout/', SignOutView.as_view(), name="logout"),
]

templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

    <link rel="icon" href="{% static 'global/assets/images/new_favicon.png' %}" sizes="32x32" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/loading-btn/loading-btn.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/iconsmind/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/index/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    
  {% block cdns %}
    
  {% endblock %}

  
  <title> {% block title %}   {% endblock %} </title>
  <style>

    main {
      background-color: #f5f5f5!important;
    }

    .badge1 {
      position:relative;
    }
    .badge1[data-badge]:after {
      content:attr(data-badge);
      position:absolute;
      top:-10px;
      right:-10px;
      font-size:.7em;
      font-family:Arial; 
      background:red;
      color:white;
      width:18px;
      height:18px;
      text-align:center;
      line-height:18px;
      border-radius:50%;
      box-shadow:0 0 1px #333;
    }


    #loader {
      transition: all .3s ease-in-out;
      opacity: 1;
      visibility: visible;
      position: fixed;
      height: 100vh;
      width: 100%;
      background: #fff;
      z-index: 90000
    }

    #loader.fadeOut {
      opacity: 0;
      visibility: hidden
    }

    .spinner {
      width: 40px;
      height: 40px;
      position: absolute;
      top: calc(50% - 20px);
      left: calc(50% - 20px);
      background-color: #333;
      border-radius: 100%;
      -webkit-animation: sk-scaleout 1s infinite ease-in-out;
      animation: sk-scaleout 1s infinite ease-in-out
    }



    @-webkit-keyframes sk-scaleout {
      0% {
        -webkit-transform: scale(0)
      }
      100% {
        -webkit-transform: scale(1);
        opacity: 0
      }
    }

    @keyframes sk-scaleout {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0)
      }
      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 0
      }
    }

    i.approval-icon{
        color: #ADFF2F
      }
      i.iconsmind-Check,  i.approval-list{
        color: #32CD32
      }

     /* {
        color: red
      } */
      .simple-icon-refresh, .simple-icon-briefcase{
        font-size: 20px;
      }
		
		.simple-icon-briefcase {
	 	    color: brown;
		}
	
    i.reservation {
      color: red;
    }

    .iconsmind-Folder-Organizing, .iconsmind-Check{
      font-size: 22px;
    }
    
    figure {
			max-width: 100%;
			position: relative;
		}
		
		figure img {
			width: 100%;
			border-radius: 8px;
			box-shadow: 0 19px 38px rgba(0,0,0,0.30),
									 0 15px 12px rgba(0,0,0,0.22)
		}


		@media (max-width: 850px){
			#logo {
				width: 175px;
				margin-top: 8px;
			}
		}
  </style>
  
</head>

<body class="app">
  <div id="loader">
    <div class="spinner"></div>
  </div>
  <script>
      window.addEventListener('load', () => {
        const loader = document.getElementById('loader');
        setTimeout(() => {
          loader.classList.add('fadeOut');
        }, 300);
      });
  </script>
<div>
    <div class="sidebar">
        <div class="sidebar-inner">
            <div class="sidebar-logo">
                <div class="peers ai-c fxw-nw">
                    <div class="peer peer-greed">
                        <a class="sidebar-link td-n" href="#">
                            <div class="peers ai-c fxw-nw">
                                <div class="peer">
                                    <div class="logo"><img id="logo" src="{% static 'global/assets/images/new_logo_consortium_azul_hrz.png' %}" width="245" height="70" style="margin-left: 8px;" alt=""></div>
                                </div>
                                <div class="peer peer-greed">
                                    <h5 class="lh-1 mB-0 logo-text" > </h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="peer">
                        <div class="mobile-toggle sidebar-toggle">
                            <a href="" class="td-n"><i class="ti-arrow-circle-left"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <ul class="sidebar-menu scrollable pos-r">

                <li class="nav-item">  
                    <a class="sidebar-link" href="{% url 'spending_control:spending-list' %}"> 
                        <span class="icon-holder">  <i id="notification-icon" class="iconsmind-Folder-Organizing" ></i> </span>
                        <span class="title"> Cobros </span>
                    </a>
                </li> 
            </ul>
        </div>
    </div>
    <div class="page-container">
        <div class="header navbar">
            <div class="header-container">
                <ul class="nav-left">
                    <li><a id="sidebar-toggle" class="sidebar-toggle" href="javascript:void(0);"><i class="ti-menu"></i></a></li>
                
                    {% block actual_page %}
                        
                    {% endblock  %}
                </ul>
                <ul class="nav-right">
                    
                    <li class="dropdown mr-2">
                        <div class="peer"><h5 class="c-grey-900 mt-3 " id="username-nav"> Bienvenido {{ user.username }} </h5></div>
                    </li>

                    <form action="" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger mt-3 mr-2 btn-sm"> Cerrar sesion </button>
                    </form>

                </ul>
            </div>
        </div>

        <main class="main-content">
            <div id="mainContent">

                {% block main %}
                
                {% endblock main %}
            </div>
        </main>

        <footer class="footer mt-auto py-3">
            <div class="container">
              <span class="text-muted">Place sticky footer content here.</span>
            </div>
        </footer>
    </div>
</div>





<script src="{% static 'js/axios.min.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/date/moment-with-locales.min.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
<script src="{% static 'css/flatpickr/flatpickr.min.js' %}"></script>
<script src="{% static 'css/flatpickr/es.js' %}"></script>  
<script src="{% static 'js/sweetalert.min.js' %}"></script>
<script type="text/javascript" src="{% static 'global/js/vendor.js' %}"></script>

{% block scripts %}
  
{% endblock  %}
</body>

</html>

templates/login.html
<!doctype html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="icon" href="{% static 'global/assets/static/images/new_favicon.png' %}" sizes="32x32" />
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <title>Sign In</title>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="{% static 'js/date/moment-with-locales.min.js' %}"></script>
  <style>
    body {
      background-color: #f5f5f5 !important;
    }

    #loader {
      transition: all .3s ease-in-out;
      opacity: 1;
      visibility: visible;
      position: fixed;
      height: 100vh;
      width: 100%;
      background: #fff;
      z-index: 90000
    }

    #loader.fadeOut {
      opacity: 0;
      visibility: hidden
    }

    .spinner {
      width: 40px;
      height: 40px;
      position: absolute;
      top: calc(50% - 20px);
      left: calc(50% - 20px);
      background-color: #333;
      border-radius: 100%;
      -webkit-animation: sk-scaleout 1s infinite ease-in-out;
      animation: sk-scaleout 1s infinite ease-in-out
    }

    @-webkit-keyframes sk-scaleout {
      0% {
        -webkit-transform: scale(0)
      }

      100% {
        -webkit-transform: scale(1);
        opacity: 0
      }
    }

    @keyframes sk-scaleout {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0)
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 0
      }
    }

    figure {
      max-width: 100%;
      position: relative;
    }

    figure img {
      width: 100%;
      border-radius: 8px;
      box-shadow: 0 19px 38px rgba(0, 0, 0, 0.30),
        0 15px 12px rgba(0, 0, 0, 0.22)
    }
  </style>
</head>


<body class="app">
  <div id="loader">
    <div class="spinner"></div>
  </div>
  <script>
    window.addEventListener('load', () => {
      const loader = document.getElementById('loader');
      setTimeout(() => {
        loader.classList.add('fadeOut');
      }, 300);
    });
  </script>
  <div class="peers ai-s fxw-nw h-100vh">
    <div class="d-n@sm- peer peer-greed h-100 pos-r bgr-n bgpX-c bgpY-c" id="login_background"
      style="background-image:url(/static/global/assets/images/new_cover_consortium.jpg);background-size: contain;">
    </div>


    <div class="col-12 col-md-4 peer pX-40 pY-80 h-100 scrollable pos-r"
      style="min-width:350px;padding-top: 20px!important;">

      <div class="d-flex justify-content-center">
        <img src="{% static 'global/assets/images/new_logo_consortium_azul.png' %}" width="250" height="170" alt="">
      </div>
      <center>
        <h2 class="fw-300 c-grey-900 mB-40 mt-4"> Inicio de sesión </h2>
      </center>

      <form id="login-form" method="POST">
        {% csrf_token %}
        {% if form.non_field_errors %}

        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <strong> {{ form.non_field_errors }} </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        <div class="form-group">
          <label for="id_username" class="text-normal text-dark">Nombre de usuario</label>
          <input type="text" class="form-control" name="username" required autofocus maxlength="100" id="id_username"
            placeholder="Inserte su nombre de usuario">
        </div>
        <div class="form-group">
          <label class="text-normal text-dark">Contrasena</label>
          <input type="password" class="form-control" required name="password" placeholder="Inserte su contrasena"
            id="id_password">

        </div>
        <div class="form-group">
          <div class="peers ai-c jc-sb fxw-nw">
            <div class="peer">
              <button type="submit" class="btn btn-primary" id="login">Login</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'global/js/vendor.js' %}"></script>
  <script type="text/javascript" src=" {% static 'global/js/bundle.js' %}"></script>
</body>

</html>